spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: localhost:3306/example
    username: example
    password: example123

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE